/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TheOfficeTest {
    @Test public void testTheOfficeHasAGreeting() {
        TheOffice classUnderTest = new TheOffice();
        assertNotNull("TheOffice should have a greeting", classUnderTest.getGreeting());
    }
}
